# Generated by Django 4.2 on 2023-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngularProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DOTNetProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FastAPIProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlaskProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlutterProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NativeAndroidProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NativeIOSProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NextJSProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PHPProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReactNativeProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReactProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpringBootProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VueProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordpressProjectEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('estimation', models.IntegerField()),
            ],
        ),
    ]
